# Generated by Django 4.2.5 on 2023-10-20 21:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("course", "buyer")},
        ),
    ]
