# Generated by Django 4.2.5 on 2023-10-10 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_article_created_at_article_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
