# Generated by Django 4.2.5 on 2023-10-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='media_link',
            new_name='img_file',
        ),
        migrations.AddField(
            model_name='course',
            name='img_file',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
