# Generated by Django 4.2.5 on 2023-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_category_remove_course_category_course_img_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ManyToManyField(related_name="courses", to="mainapp.category"),
        ),
    ]
