# Generated by Django 4.2.5 on 2023-11-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_media_link_lesson_img_file_course_img_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('about', models.TextField(blank=True)),
                ('interests', models.TextField(blank=True)),
                ('img_url', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
