# Generated by Django 4.2.5 on 2023-10-15 10:56
# Generated by Django 4.2.5 on 2023-10-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_order_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='media_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='img_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='img_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.TextField(blank=True),
        ),
    ]
