# Generated by Django 4.2.5 on 2023-10-12 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0007_order_finished"),
        ("authapp", "0002_user_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="mainapp.course",
            ),
        ),
    ]
