# Generated by Django 4.2.5 on 2023-10-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher_approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
