# Generated by Django 4.2.5 on 2023-10-25 07:33

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0003_user_is_teacher_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=authapp.models.users_avatars_path,
                verbose_name="Аватарка",
            ),
        ),
    ]
